<a href="https://colab.research.google.com/github/faranak1995/LLM_classification/blob/main/LLM_classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install transformers

In [2]:
from transformers import pipeline

In [4]:
classifier = pipeline("sentiment-analysis", device='cuda') # get a sentence and check positivity of a sentence
classifier("We are very happy!")

No model was supplied, defaulted to distilbert/distilbert-base-uncased-finetuned-sst-2-english and revision 714eb0f (https://huggingface.co/distilbert/distilbert-base-uncased-finetuned-sst-2-english).
Using a pipeline without specifying a model name and revision in production is not recommended.


[{'label': 'POSITIVE', 'score': 0.9998772144317627}]

In [5]:
from transformers import AutoTokenizer, AutoModel

In [6]:
tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")
model = AutoModel.from_pretrained("bert-base-uncased")

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/440M [00:00<?, ?B/s]

In [7]:
txt = "Hello world!"

inp = tokenizer(txt, return_tensors="pt") #pt means pytorch
out = model(**inp)
print(f"Output: {out}")

Output: BaseModelOutputWithPoolingAndCrossAttentions(last_hidden_state=tensor([[[-0.1424,  0.1335, -0.1291,  ..., -0.3597, -0.0562,  0.3605],
         [-0.3506,  0.1042,  0.6244,  ..., -0.1761,  0.4834,  0.0644],
         [-0.2451, -0.1573,  0.6945,  ..., -0.5654, -0.0894, -0.1856],
         [-0.8248, -0.9119, -0.6561,  ...,  0.5074, -0.1939, -0.1659],
         [ 0.8767,  0.0352, -0.1233,  ...,  0.2720, -0.6369, -0.1585]]],
       grad_fn=<NativeLayerNormBackward0>), pooler_output=tensor([[-8.9756e-01, -3.3040e-01, -7.6942e-01,  7.5799e-01,  4.6678e-01,
         -1.2035e-01,  9.1835e-01,  1.8087e-01, -7.2716e-01, -9.9991e-01,
         -4.4723e-01,  8.9104e-01,  9.6621e-01,  5.4915e-01,  9.4344e-01,
         -7.6605e-01, -6.0469e-01, -6.1654e-01,  4.0572e-01, -7.4644e-01,
          6.1739e-01,  9.9974e-01,  3.2991e-02,  2.5414e-01,  4.3106e-01,
          9.7732e-01, -8.4328e-01,  9.2297e-01,  9.4871e-01,  6.3994e-01,
         -7.3620e-01,  9.0956e-02, -9.7607e-01, -1.9114e-01, -8.1717e-

In [10]:
from transformers import AutoTokenizer, TFAutoModel

tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")
model = TFAutoModel.from_pretrained("bert-base-uncased")

txt = "Hello world!"

inp = tokenizer(txt, return_tensors="tf") #tf means tensorflow
out = model(**inp)
print(f"Output: {out}")

Some weights of the PyTorch model were not used when initializing the TF 2.0 model TFBertModel: ['cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.dense.weight', 'cls.predictions.bias', 'cls.seq_relationship.bias', 'cls.seq_relationship.weight', 'cls.predictions.transform.dense.bias', 'cls.predictions.transform.LayerNorm.bias']
- This IS expected if you are initializing TFBertModel from a PyTorch model trained on another task or with another architecture (e.g. initializing a TFBertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFBertModel from a PyTorch model that you expect to be exactly identical (e.g. initializing a TFBertForSequenceClassification model from a BertForSequenceClassification model).
All the weights of TFBertModel were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertModel for predictions w

Output: TFBaseModelOutputWithPoolingAndCrossAttentions(last_hidden_state=<tf.Tensor: shape=(1, 5, 768), dtype=float32, numpy=
array([[[-0.14241178,  0.13353679, -0.12907073, ..., -0.35967988,
         -0.05622256,  0.3605011 ],
        [-0.350648  ,  0.10419706,  0.6244447 , ..., -0.17610317,
          0.48340267,  0.06443428],
        [-0.24513026, -0.1573173 ,  0.6945197 , ..., -0.5654469 ,
         -0.08939926, -0.18564408],
        [-0.8247855 , -0.9119229 , -0.6560714 , ...,  0.50742465,
         -0.19388723, -0.16587655],
        [ 0.87665194,  0.03524791, -0.12331449, ...,  0.2720158 ,
         -0.6369003 , -0.15850063]]], dtype=float32)>, pooler_output=<tf.Tensor: shape=(1, 768), dtype=float32, numpy=
array([[-8.97564828e-01, -3.30401510e-01, -7.69419730e-01,
         7.57992744e-01,  4.66781229e-01, -1.20347619e-01,
         9.18352604e-01,  1.80868194e-01, -7.27160811e-01,
        -9.99908864e-01, -4.47232813e-01,  8.91044080e-01,
         9.66213107e-01,  5.49151361e-01,  9.

In [12]:
from transformers import pipeline
from transformers import AutoTokenizer, AutoModelForSequenceClassification

model_name = "distilbert-base-uncased-finetuned-sst-2-english"
model = AutoModelForSequenceClassification.from_pretrained(model_name)
tokenizer = AutoTokenizer.from_pretrained(model_name)
classifier = pipeline("sentiment-analysis", device='cuda', model=model, tokenizer=tokenizer)
results = classifier(["We are very happy to show you the Transformers library.", "We hope you don't hate it."])

for result in results:
  print(result)

config.json:   0%|          | 0.00/629 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/268M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

{'label': 'POSITIVE', 'score': 0.9997994303703308}
{'label': 'NEGATIVE', 'score': 0.5308588147163391}


In [14]:
from transformers import AutoTokenizer, AutoModelForSequenceClassification

model_name = "distilbert-base-uncased-finetuned-sst-2-english"
model = AutoModelForSequenceClassification.from_pretrained(model_name)
tokenizer = AutoTokenizer.from_pretrained(model_name)

tokens = tokenizer.tokenize("We are very happy to show you the Transformers library.")
token_ids = tokenizer.convert_tokens_to_ids(tokens)
input_ids = tokenizer("We are very happy to show you the Transformers library.")
print(f"Takens: {tokens}")
print("###"*10)
print(f"Taken IDs: {token_ids}")
print("###"*10)
print(f"Input IDs: {input_ids}")

X_train = ["We are very happy to show you the Transformers library.", "We hope you don't hate it."]
batch = tokenizer(X_train, padding=True, truncation=True,
                  max_length=512, return_tensors="pt")

print("###"*10)
print(f"Batch: {batch}")

Takens: ['we', 'are', 'very', 'happy', 'to', 'show', 'you', 'the', 'transformers', 'library', '.']
##############################
Taken IDs: [2057, 2024, 2200, 3407, 2000, 2265, 2017, 1996, 19081, 3075, 1012]
##############################
Input IDs: {'input_ids': [101, 2057, 2024, 2200, 3407, 2000, 2265, 2017, 1996, 19081, 3075, 1012, 102], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}
##############################
Batch: {'input_ids': tensor([[  101,  2057,  2024,  2200,  3407,  2000,  2265,  2017,  1996, 19081,
          3075,  1012,   102],
        [  101,  2057,  3246,  2017,  2123,  1005,  1056,  5223,  2009,  1012,
           102,     0,     0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0]])}


In [18]:
from transformers import AutoTokenizer, AutoModelForSequenceClassification
import torch
import torch.nn.functional as F

model_name = "distilbert-base-uncased-finetuned-sst-2-english"
model = AutoModelForSequenceClassification.from_pretrained(model_name)
tokenizer = AutoTokenizer.from_pretrained(model_name)

X_train = ["We are very happy to show you the Transformers library.", "We hope you don't hate it."]
batch = tokenizer(X_train, padding=True, truncation=True,
                  max_length=512, return_tensors="pt")

print(f"Batch: {batch}")
print("###"*10)

with torch.no_grad():
  outputs = model(**batch)
  print(f"Output: {outputs}")
  print("###"*10)
  predictions = F.softmax(outputs.logits, dim=1) # the summation of neurons' weight will be 1
  print(f"Predictions: {predictions}") # show from the highest weight in two classes
  print("###"*10)
  labels = torch.argmax(predictions, dim=1)
  print(f"Labels: {labels}")
  print("###"*10)
  labels = [model.config.id2label[label_id] for label_id in labels.tolist()]
  print(f"Labels: {labels}")

Batch: {'input_ids': tensor([[  101,  2057,  2024,  2200,  3407,  2000,  2265,  2017,  1996, 19081,
          3075,  1012,   102],
        [  101,  2057,  3246,  2017,  2123,  1005,  1056,  5223,  2009,  1012,
           102,     0,     0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0]])}
##############################
Output: SequenceClassifierOutput(loss=None, logits=tensor([[-4.1329,  4.3811],
        [ 0.0818, -0.0418]]), hidden_states=None, attentions=None)
##############################
Predictions: tensor([[2.0060e-04, 9.9980e-01],
        [5.3086e-01, 4.6914e-01]])
##############################
Labels: tensor([1, 0])
##############################
Labels: ['POSITIVE', 'NEGATIVE']
